In [14]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
price=np.array([100,101,102,103,104])
returns=(price[1:]-price[:-1])/price[:-1]
print('Daily Returns:',returns)

Daily Returns: [0.01       0.00990099 0.00980392 0.00970874]


In [24]:
from sklearn.preprocessing import MinMaxScaler
data=np.array([[10,200],[15,300],[20,400]])
#data
scaler=MinMaxScaler()
scaled=scaler.fit_transform(data)
print(scaled)
min_vals=data.min(axis=0)
max_vals=data.max(axis=0)
scaled_up=(data-min_vals)/(max_vals-min_vals)
print(min_vals)
print(max_vals)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
[ 10 200]
[ 20 400]


In [28]:
result=[]
for i in range(1000000):
    result
arr=np.arange(100)
result_np=arr*2
result_np

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [29]:
arr2d=np.array([[1,2],[3,4]])
print(arr2d)
print(arr.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.dtype)

[[1 2]
 [3 4]]
1
(2, 2)
4
int32


In [37]:
np.zeros((2,3))
np.ones((2,3))
np.eye(3)
np.full((2,2),7)
np.arange(0,10,2)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
a=np.arange(6)
b=a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
a=np.array([[1,2],[3,4]])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))

10
4
1
2.5
1.118033988749895


In [43]:
a=np.array([1,2,3,4,5])
print(a[a<=3])

[1 2 3]


In [44]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
c=a.view()
c[0]=200
print(a)

[100   2   3]
[200   2   3]


In [45]:
a=np.array(([1,2,3],[4,5,6]))
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
a=np.array([[1,2],[3,4]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[4 6]
[3 7]


In [49]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [51]:
a=np.array([1,2,3,4,5,6])
print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [52]:
a=np.array([[1],[2],[3]])
b=np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [53]:
a=np.array([1,2,3,4])
print(np.any(a>2))
print(np.all(a>0))

True
True


In [54]:
a=np.array([1,2,3,4,5])
print(np.where(a>2, "High", "Low"))

['Low' 'Low' 'High' 'High' 'High']
